services:
  fluentd:
    image: grafana/fluent-plugin-loki:main
    volumes:
     - ./fluentd/config.conf:/fluentd/etc/fluent.conf
    environment:
     - LOKI_URL=http://loki-gateway
     - TZ=Etc/UTC
    networks:
     - loki
    depends_on:
     - loki-gateway
    ports:
     - 514:514/udp
