version: "3"


services:
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - TZ=Etc/UTC
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./grafana/storage:/var/lib/grafana 
    image: grafana/grafana:latest
    ports:
      - "8091:3000"
    networks:
      - loki
    depends_on:
      - mimir-lb
      - loki-gateway