global:
  scrape_interval: 5s
  external_labels:
    cluster: infra
    namespace: infra

scrape_configs:
  - job_name: infra/mimir
    static_configs:
      - targets: ["mimir-0:8080"]
        labels:
          pod: "mimir-0"
      - targets: ["mimir-1:8080"]
        labels:
          pod: "mimir-1"
      - targets: ["mimir-2:8080"]
        labels:
          pod: "mimir-2"
      - targets: ["grafana:3000"]
        labels:
          pod: "grafana"
      - targets: ["loki-read:3100"]
        labels:
          pod: "loki-read"
      - targets: ["loki-write:3100"]
        labels:
          pod: "loki-write"
      - targets: ["loki-backend:3100"]
        labels:
          pod: "loki-backend"

remote_write:
  - url: http://mimir-lb:9009/api/v1/push
    headers:
      X-Scope-OrgID: fake
