apiVersion: 1
datasources:

 - name: Loki
   type: loki
   access: proxy
   orgId: 1
   url: http://loki-gateway
   basicAuth: false
   isDefault: false
   version: 1
   editable: false
   jsonData:
    httpHeaderName1: "X-Scope-OrgID"
   secureJsonData:
    httpHeaderValue1: "fake"

 - name: Mimir
   type: prometheus
   access: proxy
   orgId: 1
   url: http://mimir-lb:9009/prometheus
   version: 1
   editable: true
   isDefault: true
   jsonData:
    httpHeaderName1: "X-Scope-OrgID"
    alertmanagerUid: "alertmanager"
   secureJsonData:
    httpHeaderValue1: "fake"

 - name: Mimir Alertmanager
   uid: alertmanager
   type: alertmanager
   access: proxy
   orgId: 1
   url: http://mimir-lb:9009/
   version: 1
   editable: true
   jsonData:
    httpHeaderName1: "X-Scope-OrgID"
    implementation: "mimir"
   secureJsonData:
    httpHeaderValue1: "fake"
